# Generated by Django 3.2.7 on 2021-10-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_superhero_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='details',
            field=models.TextField(max_length=1000),
        ),
    ]
