# Generated by Django 3.2.7 on 2021-10-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_alter_superhero_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superhero',
            name='details',
        ),
        migrations.AddField(
            model_name='superhero',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superhero',
            name='strength',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superhero',
            name='weakness',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='superhero',
            name='identity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
