# Generated by Django 3.2.7 on 2021-10-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_auto_20211006_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='strength',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='weakness',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
