# Generated by Django 3.2.8 on 2021-11-01 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hero', '0006_auto_20211008_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superhero',
            name='description',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='image',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='weakness',
        ),
        migrations.AddField(
            model_name='superhero',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=100)),
                ('image', models.CharField(default='None', max_length=100)),
                ('description', models.TextField(default='None')),
                ('strength', models.CharField(default='None', max_length=100)),
                ('weakness', models.CharField(default='None', max_length=100)),
                ('superhero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.superhero')),
            ],
        ),
    ]
